### ISSUE TITLE
Calender Input

### ISSUE THREAD

**Issue by tanushgolwala** [ACM-VIT/carpoolit-app#1]
![Profile Creation](https://github.com/ACM-VIT/carpoolit-app/assets/115440133/32c13416-962c-4d66-8a18-134e5777e2af)
![Calendar](https://github.com/ACM-VIT/carpoolit-app/assets/115440133/2a8b7c2a-0418-4d8f-b049-0ae1a68e4e97)

The designs can also be found here:
[https://www.figma.com/file/dJGy6BFj4u2ZNRNhi6XeMl/Carpool-by-ACM-VIT?type=design&node-id=225-1731&mode=design&t=jK91zZGwOaaWEU4U-0](url)

The screens will go under carpoolit-app/screens

**Comment by eshita241** [comment]
I would like to do this.

**Comment by tanushgolwala** [comment]
#25
