### ISSUE TITLE
Calendar Component

### ISSUE THREAD

**Issue by JuxtaRYCT** [ACM-VIT/carpoolit-app#12]
Create a calendar component to be used throughout the Host Ride and Join Ride pages. 

![Calendar_carpoolIT](https://github.com/ACM-VIT/carpoolit-app/assets/116808459/ad98a5f0-d130-4b32-9338-2ca84e116711)

The design can be found in the Figma file(https://www.figma.com/file/dJGy6BFj4u2ZNRNhi6XeMl/Carpool-by-ACM-VIT?type=design&node-id=7%3A205&mode=design&t=GH6lPpa0UtFMurtk-1)

**Comment by eshita241** [comment]
..
