### ISSUE TITLE
Interested Riders Card component

### ISSUE THREAD

**Issue by JuxtaRYCT** [ACM-VIT/carpoolit-app#14]
Create the component which is used on the interested riders page:

![Interested Riders_carpoolIT](https://github.com/ACM-VIT/carpoolit-app/assets/116808459/57daa654-7eca-4501-be13-f91eb04910bc)

The design can be found in the Figma file(https://www.figma.com/file/dJGy6BFj4u2ZNRNhi6XeMl/Carpool-by-ACM-VIT?type=design&node-id=7%3A205&mode=design&t=GH6lPpa0UtFMurtk-1)

**Comment by tanushgolwala** [comment]
I'll do this
