### ISSUE TITLE
Text-Fields input Component

### ISSUE THREAD

**Issue by JuxtaRYCT** [ACM-VIT/carpoolit-app#15]
Create the text-field input element which will be used for taking inputs throughout the app.

![TextField_carpoolIT](https://github.com/ACM-VIT/carpoolit-app/assets/116808459/226f8ef1-8990-4a4f-8eeb-c863e596a4f5)

The design can be found in the Figma file(https://www.figma.com/file/dJGy6BFj4u2ZNRNhi6XeMl/Carpool-by-ACM-VIT?type=design&node-id=7%3A205&mode=design&t=GH6lPpa0UtFMurtk-1)

**Comment by harshitaak07** [comment]
meee

**Comment by JuxtaRYCT** [comment]
Component already created in joinListItem.tsx file.
