### ISSUE TITLE
JoinRide Page

### ISSUE THREAD

**Issue by tanushgolwala** [ACM-VIT/carpoolit-app#2]
![Join a Ride](https://github.com/ACM-VIT/carpoolit-app/assets/115440133/45cb6539-012e-4570-88d9-78c13e172316)

[https://www.figma.com/file/dJGy6BFj4u2ZNRNhi6XeMl/Carpool-by-ACM-VIT?type=design&node-id=225-1731&mode=design&t=jK91zZGwOaaWEU4U-0](url)

The screens will go under carpoolit-app/screens

**Comment by harshitaak07** [comment]
meeeee
