### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by JuxtaRYCT** [ACM-VIT/carpoolit-app#20]
Create the splash screen for the carpoolIT application, the 2 pages in the splash screen are shown below:

![Splash Screen-1](https://github.com/ACM-VIT/carpoolit-app/assets/116808459/0471bcbd-a011-4509-966c-1b59add74f24)
![Splash Screen-2](https://github.com/ACM-VIT/carpoolit-app/assets/116808459/83601f08-8ef4-47f1-acdf-ee2507db16d0)

All the assets can be found from the design file available at- https://www.figma.com/file/dJGy6BFj4u2ZNRNhi6XeMl/Carpool-by-ACM-VIT?type=design&node-id=225%3A1353&mode=design&t=754H9poSWeontvHB-1

**Comment by JuxtaRYCT** [comment]
Lord Rohan

**Comment by tanushgolwala** [comment]
Lord Rohan

**Comment by aastikn** [comment]
Lord Rohan

**Comment by mananssh** [comment]
Lord Rohan
