### ISSUE TITLE
Request Ride Page

### ISSUE THREAD

**Issue by tanushgolwala** [ACM-VIT/carpoolit-app#3]
![Request ride](https://github.com/ACM-VIT/carpoolit-app/assets/115440133/e057a1c5-59a9-47d9-b2df-678fd2c16603)

[https://www.figma.com/file/dJGy6BFj4u2ZNRNhi6XeMl/Carpool-by-ACM-VIT?type=design&node-id=7-205&mode=design&t=jK91zZGwOaaWEU4U-0](url)

The screens will go under carpoolit-app/screens

**Comment by JuxtaRYCT** [comment]
I'm interested in taking this issue.

**Comment by harshitaak07** [comment]
will take this, if no one has

**Comment by tanushgolwala** [comment]
Cant self assign 😭
