### ISSUE TITLE
Available Rides Page

### ISSUE THREAD

**Issue by tanushgolwala** [ACM-VIT/carpoolit-app#4]
![Available Rides](https://github.com/ACM-VIT/carpoolit-app/assets/115440133/7599bb8a-a7e7-429d-9cf3-f362d27adde1)

[https://www.figma.com/file/dJGy6BFj4u2ZNRNhi6XeMl/Carpool-by-ACM-VIT?type=design&node-id=7-205&mode=design&t=jK91zZGwOaaWEU4U-0](url)

The screens will go under carpoolit-app/screens

**Comment by mananssh** [comment]
I'll take this?
