### ISSUE TITLE
Interested Riders Page

### ISSUE THREAD

**Issue by tanushgolwala** [ACM-VIT/carpoolit-app#6]
![Interested Riders](https://github.com/ACM-VIT/carpoolit-app/assets/115440133/f54caeb1-d158-43b9-8532-47ca65c13f8c)

[https://www.figma.com/file/dJGy6BFj4u2ZNRNhi6XeMl/Carpool-by-ACM-VIT?type=design&node-id=225-687&mode=design&t=jK91zZGwOaaWEU4U-0](url)

The screens will go under carpoolit-app/screens

**Comment by harshitaak07** [comment]
will take this
