### ISSUE TITLE
Host Ride Page

### ISSUE THREAD

**Issue by tanushgolwala** [ACM-VIT/carpoolit-app#7]
![Host a Ride](https://github.com/ACM-VIT/carpoolit-app/assets/115440133/d17ff814-31d9-4dbe-b1a2-d76e7df7978a)

[https://www.figma.com/file/dJGy6BFj4u2ZNRNhi6XeMl/Carpool-by-ACM-VIT?type=design&node-id=225-687&mode=design&t=jK91zZGwOaaWEU4U-0](url)
The screens will go under carpoolit-app/screens

**Comment by aastikn** [comment]
May thou bestoweth this issue on me?
