### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by tanushgolwala** [ACM-VIT/carpoolit-app#8]
![Profile Page](https://github.com/ACM-VIT/carpoolit-app/assets/115440133/6b09550d-e9f8-4d1d-a012-61c061d143c3)

[https://www.figma.com/file/dJGy6BFj4u2ZNRNhi6XeMl/Carpool-by-ACM-VIT?type=design&node-id=225-437&mode=design&t=PUOffIJ9wGlaxVSx-0](url)

The screens will go under carpoolit-app/screens

**Comment by JuxtaRYCT** [comment]
Can I take this up?

**Comment by JuxtaRYCT** [comment]
@RohanKhatua this issue can be closed now, it was merged along with the RideCard component.
